### ISSUE TITLE
Question: Way to prevent access for certain users

### ISSUE THREAD

**Issue by aleksano** [JohnDoh/Roundcube-Plugin-Global-Address-Book#37]
Hi!
Thanks for good plugin.
Possible to prevent access of certain users to their domain global address book?

**Comment by JohnDoh** [comment]
not from within this plugin. you would need to change your roundcube config based on the user for who has access. please use the roundcube forum for support not this bug tracker.

**Comment by aleksano** [comment]
Thanks for your assistance.
