### ISSUE TITLE
setting allow group in global addressbook not working

### ISSUE THREAD

**Issue by johanpeters** [JohnDoh/Roundcube-Plugin-Global-Address-Book#39]
// allow groups in global address book
$config['globaladdressbook_groups'] = true;

but i am still unable to greate a group in the global addressbook (option is grayd out.)

**Comment by JohnDoh** [comment]
this is not a support forum please use the roundcube mailinglists or forum

**Comment by johanpeters** [comment]
Okay,.. tnx.. 

 

I post it on roundcube forum.. 

 

 

 

Van: JohnDoh [mailto:notifications@github.com] 
Verzonden: woensdag 6 januari 2016 09:20
Aan: JohnDoh/Roundcube-Plugin-Global-Address-Book <Roundcube-Plugin-Global-Address-Book@noreply.github.com>
CC: johanpeters <j.peters@itics.nl>
Onderwerp: Re: [Roundcube-Plugin-Global-Address-Book] setting allow group in global addressbook not working (#39)

 

this is not a support forum please use the roundcube mailinglists or forum
