### ISSUE TITLE
Birthdays do not Display in Calendar

### ISSUE THREAD

**Issue by rmcaninch** [JohnDoh/Roundcube-Plugin-Global-Address-Book#41]
I have this calendar https://git.kolab.org/diffusion/RPK/ plugin and it will display birthdays from the Personal Addressbook but not from this Global Addressbook.

Actually, if I turn on both the personal addressbook birthdays and this global addressbook it prevents the ones from the personal addressbook from showing.

It is minor issue, nut sure which plugin is causing the issue.

**Comment by JohnDoh** [comment]
i would guess the issue is in the calendar plugin but I cannot be sure since I do not know anything about that plugin. Will have to wait and see what they say about it.

**Comment by rmcaninch** [comment]
This fix appears to work.
http://www.roundcubeforum.net/index.php/topic,23476.0.html
