### ISSUE TITLE
Not Global

### ISSUE THREAD

**Issue by synergia-developers** [JohnDoh/Roundcube-Plugin-Global-Address-Book#42]
I installed the current version 1.9 on RC version 1.1.4,  I change the admin, and it works fine but the username (tried both existing and not existing) are not working. 

- Not existing username doesn't auto create. 
- RC adds a Global Addresses folder but not global. As I add new contact using admin it won't be added to other users' Global Addresses folder.

I did search about this issue but no luck on how to fix this.

Thanks!

**Comment by JohnDoh** [comment]
try with all other plugins disabled. please provide config details.

**Comment by synergia-developers** [comment]
It's the default setting of inmotion's vps server, the RC's config file has 1150 lines of code. I see they use $config['address_book_type'] = 'sql'; and I tried putting 'ldap' and '' then the personal addresses folder just disappeared and still the global addresses folder does not become global. I also tried setting 

$config['plugins'] = array('globaladdressbook','cpanellogin','cpanellogout');

into 

$config['plugins'] = array('globaladdressbook');

and still it does not work.. I am new to this RC configuration so I can't provide other information.. perhaps you can tell me where to look for them.

**Comment by JohnDoh** [comment]
i meant the config details from the globaladdressbook config. also please check your roundcube error log for an related info

**Comment by synergia-developers** [comment]
$config['globaladdressbook_user'] = 'miko@%h';
$config['globaladdressbook_perms'] = 0;
$config['globaladdressbook_force_copy'] = true;
$config['globaladdressbook_groups'] = false;
$config['globaladdressbook_admin'] = 'miko@domain.com';
$config['globaladdressbook_autocomplete'] = true;
$config['globaladdressbook_check_safe'] = true;

I also tried 'miko@%h' and 'miko' for the user.. No luck..

**Comment by synergia-developers** [comment]
I also can't find the error log for roundcube specifically.. got no /var/cpanel/roundcube/errors and /var/cpanel/roundcube/sendmail on our server

**Comment by synergia-developers** [comment]
And I also notice that if I tried to set $config['globaladdressbook_user'] = 'miko@%d' or 'miko@domain.com', both Global Addresses folder and the Personal Addresses folder work as if they are collecting contacts from a single source, so if I added a contact in Global, the contact will be added in Personal, same as deleting contacts.

**Comment by JohnDoh** [comment]
you cannot use miko@domain.com for the globaladdressbook_user since that is the same as your username. the globaladdressbook_user must be its own user. its a fake username it does not have to exist as an actual user on your mail server its just the account where the global addresses are stored in the roundcube database.

**Comment by synergia-developers** [comment]
This issue hasn't been solved. To those who run into this issue as well, please advice me how to solve it. Thanks!

**Comment by JohnDoh** [comment]
What you have described is a configuration issue not a bug. You cannot set the globaladdressbook_user to a real username. For example if you set it as [global_addressbook_user] (the default) then the first time the plugin is loaded you'll see this user created in the roundcube users table. After that any contact is stored under this user and will be visible to all users who have access to the globaladdressbook. For more information about the username please see the readme.
