### ISSUE TITLE
PHP 5.6 or 7.0

### ISSUE THREAD

**Issue by johanpeters** [JohnDoh/Roundcube-Plugin-Global-Address-Book#43]
Hello,

the hosting provider is switched from php 5.5 to 7.0 and now roundcube with this plugin enabled does not work anymore.

for now i have disabled globaladdresbook plugin and roundcube is working again.
but we need the global addresbook functionality.

**Comment by JohnDoh** [comment]
I do not have access to any server running PHP7. Please provide the error from the Roundcube error log or better still a patch for the plugin. Thanks.

**Comment by johanpeters** [comment]
Hello John,

 

I have read the error log one more time.. my fault.. 

In the config file of globaladdressbook there was a error.

 

I changed it.. and now its working again.

 

With regards,

 

 

Van: JohnDoh [mailto:notifications@github.com] 
Verzonden: zaterdag 4 februari 2017 08:14
Aan: JohnDoh/Roundcube-Plugin-Global-Address-Book <Roundcube-Plugin-Global-Address-Book@noreply.github.com>
CC: johanpeters <j.peters@itics.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [JohnDoh/Roundcube-Plugin-Global-Address-Book] PHP 5.6 or 7.0 (#43)

 

I do not have access to any server running PHP7. Please provide the error from the Roundcube error log or better still a patch for the plugin. Thanks.
